### ISSUE TITLE
Introduce ITimeMachine

### ISSUE THREAD

**Issue by rasmus** [rasmus/EventFlow#43]
Create a service for getting `DateTimeOffset.Now` to make it easier to test time.

**Comment by rasmus** [comment]
Wait until someone actually has a good idea (and need) before implementing this

**Comment by Yaevh** [comment]
As of v0.80.4377, event timestamp is generated by a call to `DateTimeOffset.Now` inside `AggregateRoot.Emit()`. You can pass custom `IMetadata` to it, but trying to set `IMetadata.Timestamp` like this leads to `ArgumentException` later on.

I see the following potential methods to inject `DateTimeOffset` into `IMetadata`:
1. Make `AggregateRoot.Emit()` take an optional `DateTimeOffset` parameter; if provided, it would be used instead of `DateTimeOffset.Now`
2. Inject `ITimeMachine` (or some other `IClock`) into `AggregateRoot` constructor
3. Do not set `IMetadata.Timestamp` when emitting event, but only during `AggregateRoot.CommitAsync()` or `IAggregateStore.UpdateAsync()` - then we have an option to easily inject services, including `ITimeMachine`
4. Defer creation of `IMetadata` altogether from `AggregateRoot.Emit()` to `AggregateRoot.CommitAsync()`

Option 1 is the simplest one, but would require explicit opt-in on the part of the user, which may or may not be a good thing. It would also not only facilitate testing, but also allow backdating of emitted events, which again may or may not be a good idea.
Option 2 would theoretically be most compatible with DI, but also be a major breaking change and thus a royal pain in the ass for not-so-great gain.
Option 3 would be mostly transparent to user, but modifying `IMetadata` in two steps in two different places would lead to rather hard-to-follow code, which doesn't seem like a good idea to me.
Option 4 would evade option 3's problem, but would require another breaking change, that being removal of `IUncommittedEvent.IMetadata` (and effectively also `IUncommittedEvent`, as it would now be just a dumb container for `IAggregateEvent`). It would also break any code that depends on `IMetadata` being created right there with the event itself, but I'm not actually convinced that accessing `IMetadata` of an uncommitted event is a good idea.
