### ISSUE TITLE
Why does Command.Publish() require a CancellationToken?

### ISSUE THREAD

**Issue by JC008** [rasmus/EventFlow#84]
`Command.Publish()` uses an async adapter internally but externally presents itself as not being `async` and the need to pass a `cancellationToken` parameter appears confusing.

**Comment by rasmus** [comment]
@JC008 EventFlow is async first and therefor you should always use the async methods as EventFlow merely tries to do a good job when using the sync methods. Sync methods are exposed on interfaces as a convenience to be used externally by developers, but never used internally.

The use of cancellation tokens isn't something that's "async only", its a generic way of cancelling started work, which is why its exposed on almost all EventFlow interfaces. EventFlow uses retry strategies, in which it might wait a tiny bit (currently only for optimistic concurrency exceptions). So, cancellation tokens are exposed on every method what might result in work that's either IO bound or might have a retry strategy.

At a later time I'll let developers be able to configure the "point of no return" internally in EventFlow. Some developers might always be able to cancel an action, but some might not want to cancel if the aggregate events have been committed and read models are being updated.

You are always free to create an extension method in your own application that sends `CancellationToken.None` to e.g. `Publish(...)`.

I hope that answers your question?

**Comment by JC008** [comment]
Yes thanks.
