### ISSUE TITLE
Convert Build Workflow from Appveyor to Github Actions

### ISSUE THREAD

**Issue by WardenUnleashed** [rasmus/EventFlow#872]
I noticed there was some work on this done in the `develop-v0` branch. I also was [working on some of that in my sparetime](https://github.com/WardenUnleashed/EventFlow) and figured we might want to consolidate or at least have a place to discuss the status of it!

PS: I would assign this to the milestone but I don't think I have permissions to

**Comment by rasmus** [comment]
GitHub Actions have been enabled for v1
https://github.com/eventflow/EventFlow/pull/852

But since Linux containers aren't possible on GitHub Actions, it isn't really possible for v0
https://github.com/eventflow/EventFlow/pull/850

**Comment by rasmus** [comment]
Here's the issue related to running Linux containers on Windows VMs in GitHub Action runners
https://github.com/actions/virtual-environments/issues/2216

**Comment by WardenUnleashed** [comment]
@rasmus I see. I haven't entirely finished it yet but instead of just running the `build.ps1` script, I was converting the whole process into [github action steps](https://github.com/WardenUnleashed/EventFlow/blob/develop-v0/.github/workflows/build.yml) and it seemed to be working to at least build and run the unit tests for  `develop-v0` successfully. I can continue working towards that goal if you want?

Additionally, in order to get this working I dropped .NET framework in version 0.x and normalized everything to `netstandard2.1` and `netcoreapp3.1`. I also deleted `EventFlow.Owin`(I didn't see any way to upgrade this to netcore).

Should I submit a MR to get those pieces in to `v0` or do we have some kind of plan to drop support gradually?

**Comment by rasmus** [comment]
v0 still needs to support .NET Framwork and since GitHub actions already work on v1 using the `build.ps1` on .NET Core 2.1 and upwards, I think that I'll stick with that. When v1 has been fully released, v0 and v1 can start to have different build setups and AppVeyor can be completely removed when v0 is no longer maintained.

In short, the build setup already in place for v0 and v1, with GitHub Actions merely being a quick feedback, is good enough for now.

**Comment by rasmus** [comment]
Done
